name: MYPYC Run

on: [push, pull_request]

jobs:
  detection_coverage:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9, "3.10"]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install -U pip setuptools
        pip install -r dev-requirements.txt
        pip uninstall -y charset-normalizer
    - name: Install the package
      env:
        CHARSET_NORMALIZER_USE_MYPYC: '1'
      run: |
        python -m build --no-isolation
        pip install ./dist/*.whl
    - name: Clone the complete dataset
      run: |
        git clone https://github.com/Ousret/char-dataset.git
    - name: Coverage WITH preemptive
      run: |
        python ./bin/coverage.py --coverage 97 --with-preemptive
    - name: Coverage WITHOUT preemptive
      run: |
        python ./bin/coverage.py --coverage 95
